### ISSUE TITLE
Improve documentation of devices

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/pennylane-qiskit#2]
It would be great if the devices were documented a bit more thoroughly.

The IBM device for example claims to be "A PennyLane qiskit.ibm device for the Qiskit Local Simulator backend.", which is not what it actually is, I think, and for a new user it will be hard to know the difference between 

* AerQiskitDevice | A PennyLane `qiskit.aer` device for the Qiskit Simulator Aer (local) backend.
 
and 

* BasicAerQiskitDevice | A PennyLane `qiskit.basicaer` device for the Qiskit Local Simulator backend.

It would be great if explicite links to the respective devices' descriptions in the qiskit documentation would be provided.

The naming of device classes could probably also be improved.

**Comment by carstenblank** [comment]
Alright, fair issue. Do you have a suggestion as to how to name the device classes? I thought this would be very appropriate... however, I am just using the nomenclature of IBM Q. Regarding the `qiskit.ibm` topic, I will look into it, that would indeed be a false statement and needs fixing.

**Comment by carstenblank** [comment]
@cgogolin do you think this is a good fix?

**Comment by carstenblank** [comment]
There is another PR: #31 with a bit more fixes. I hope the docs are getting better now...

**Comment by cgogolin** [comment]
Looks good. Thanks for continuing the development of this!

**Comment by co9olguy** [comment]
I was just looking around the `devices.py` file and I noticed a few places where the docstrings will need to be updated to reflect new class structures of the core pennylane library.

Specifically, the docstring references to `pennylane.expval.PauliX` etc. will need to now point to the new locations of these observables e.g., (`pennylane.ops.PauliX`)
