### ISSUE TITLE
Support more expectation values

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane-qiskit#28]
Currently, the Qiskit devices only allow for `PauliZ` expectation values.

However, it is simple to support _all_ the remaining PennyLane expectation values: `PauliX`, `PauliY`, `Hadamard`, and `Hermitian`.

---

For the first three, this is relatively simple, and can be done as follows:

![image](https://user-images.githubusercontent.com/2959003/57975062-c3e00200-7990-11e9-8894-eba25eab8e29.png)

That is,

1. Peak at the expectation queue using `self.expval_queue`

2. Apply the corresponding change of basis unitary U as per the table above

3. Return to the user the resulting \<Z\> expectation value

---

For arbitrary 2x2 Hermitian matrices, the process is only slightly more complicated:

![image](https://user-images.githubusercontent.com/2959003/57975087-34871e80-7991-11e9-8f81-51581a90148a.png)

That is:

1. Calculate the eigenvector matrix U and the corresponding eigenvalues lambda of the provided Hermitian matrix

2. Apply the change of basis matrix U^\dagger to the end of the users circuit

3. Measure the wavefunction probabilities p

4. The resulting expectation value is given by the dot product lambda.p

**Comment by josh146** [comment]
For example, see how this is done in the PennyLane-Forest plugin, here:

https://github.com/rigetti/pennylane-forest/blob/multi_qubit_observables/pennylane_forest/qvm.py

Specifically, the `pre_expval` and `expval` methods.

**Comment by carstenblank** [comment]
Nice! Thank you so much Josh! I will implement this the next days I think!

**Comment by josh146** [comment]
Let me know if you have any questions!

**Comment by carstenblank** [comment]
Do you think we solved this issue with #32 ?

**Comment by josh146** [comment]
I think it is, yes :slightly_smiling_face: - more features can still be added (such as multi-qubit expectations), but that is out of scope and can be discussed in a new issue.
