### ISSUE TITLE
Support devices with noise model 

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/pennylane-qiskit#3]
One of the great things about qiskit is that it has backends with realistic noise models and one of the greta things about PennyLane and variational approaches to quantum computing is that they probably work well even in the presence of noise. 

It would thus be highly desirable to expose the noise model features of the PL qiskit devices to the user and allow to specify a noise model for such a device via, e.g., a keyword argument such as
```
dev = qml.device('qiskit.basicaer', wires=2, noise_model='basic_device_noise_model')
```
which would then be taken into account when instantiating the `backend` in `pre_expval()`.

**Comment by carstenblank** [comment]
So, with the PR #22 this is finally addressed. I will add the changes, after review & tests into master.

**Comment by carstenblank** [comment]
I think this should be fixed by now. Re-open if the problem remains.
