### ISSUE TITLE
Update the plugin to work with v0.4 of PennyLane

### ISSUE THREAD

**Issue by josh146** [XanaduAI/pennylane-qiskit#33]
PennyLane v0.4 introduces some breaking changes:

* `qml.expval.Observable()` is now `qml.expval(qml.observable())`

* The required `Device.expectations` property is now named `Device.observables`

* The `pre_expval` and `post_expval` methods are now named `pre_measure` and `post_measure`.

These will have to be updated across the plugin and tests.

**Comment by quantshah** [comment]
#34 takes care of this. Next up

- Update README and plugin docs with the easiest way to add token and run a quatum function
- Make a new release for the plugin
- Update pennylane docs with the latest plugin information.
- Refactor more tests to pytests

**Comment by josh146** [comment]
@quantshah, can this issue now be closed?

**Comment by quantshah** [comment]
Yes. :-)
