### ISSUE TITLE
Can't instantiate abstract class AerQiskitDevice with abstract methods expectations

### ISSUE THREAD

**Issue by maxiwelian** [XanaduAI/pennylane-qiskit#37]
**Describe the bug**
Can't instantiate abstract class AerQiskitDevice with abstract methods expectations

**To Reproduce**
import pennylane as qml
dev = qml.device('qiskit.aer', wires=2)

**Expected behavior**
Initializes device 

**Screenshots**
Traceback (most recent call last):
  File "/home/amwilso4/projects/qaoa_pipeline/qaoa/penny_run.py", line 16, in <module>
    dev = qml.device('qiskit.aer', wires=2)
  File "/home/amwilso4/projects/qaoa_pipeline/src/pennylane/pennylane/__init__.py", line 202, in device
    return plugin_device_class(*args, **options)
TypeError: Can't instantiate abstract class AerQiskitDevice with abstract methods expectations

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - Browser chomium
 - Version 42

**Additional context**
There's clearly something going on with my environment, hoping someone has seen this bug before. 

>>> import pennylane_qiskit as pq
>>> qiskit.__version__
'0.8.1'
>>> qml.__version__
'0.4.0-dev0'
>>> pq.__version__
'0.0.8'

**Comment by quantshah** [comment]
Can you tell us the qiskit version? And also the pennylane and qiskit
plugin versions? We recently had some breaking changes to pennylane and
just updated the plugins to work on the latest versions of pennylane (0.4)
and qiskit (0.10)

**Comment by maxiwelian** [comment]
In the 'additional context' section.

Here for reference 
import pennylane_qiskit as pq
qiskit.version
'0.8.1'
qml.version
'0.4.0-dev0'
pq.version
'0.0.8'

**Comment by josh146** [comment]
Hi @maxiwelian, can you try upgrading your installed versions of both PennyLane and PennyLane-Qiskit:
```bash
pip install pennylane pennlane-qiskit --upgrade
```

It looks like you are using an older development version of PennyLane, last week, we released the final 0.4 release of PennyLane.

**Comment by MBrandt-NASA** [comment]
Note -- there was a misprint "pennlane-qiskit" should have been "pennylane-qiskit" 😉 for anyone who was just quickly copy-pasting the pip install line.

Furthermore, I had the same (original) problem and what finally worked for me was:

`python -m pip install pennylane pennylane-qiskit --upgrade`

I hope that helps.  😃

**Comment by josh146** [comment]
Thanks for the catch @MBrandt-NASA! I'll fix that up now.

**Comment by josh146** [comment]
Closing now that all PyPI releases are up to date (and in sync)
