### ISSUE TITLE
Hermitian op only works for single-qubit observables

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane-qiskit#40]
The base PennyLane library now how support for multi-qubit Hermitian observables (see [here](https://github.com/XanaduAI/pennylane/pull/192)). However, the pennylane-qiskit plugin only works for single-qubit observables. 

@quantshah @josh146 Are there any restrictions in qiskit that prevent us from implementing support for multi-qubit Hermitian observables?

**Comment by josh146** [comment]
No, it is just a matter of implementing it. This has already been implemented on hardware devices over at https://github.com/rigetti/pennylane-forest, see [qvm.py](https://github.com/rigetti/pennylane-forest/blob/master/pennylane_forest/qvm.py). I can outline the process here.

1. Before executing the device, 'peak' at the observable queue in `pre_measure`. If an Hermitian observable exists in the queue, compute the eigendecomposition U D U^\dagger.

    Store the eigenvalues for later, and prepend the unitary U^\dagger to the end of the operation queue.

    _This step should already be implemented, as it is required for arbitrary single-qubit Hermitian observables._

2. After device execution, in both `var` and `expval`:
    
    - For only the subsystems in which the multi-qubit observable is measured on, compute the probability distribution over all computational basis states.

      This could be done manually from the sampling results (see the PennyLane-Forest [`QVMDevice.probabilities()`](https://github.com/rigetti/pennylane-forest/blob/master/pennylane_forest/qvm.py#L214) method), or perhaps Qiskit provides built in functions for this ( `results.get_counts()`?)

3. Expectation values are then given by `D @ probs`

4. Variance values are given by `(D ** 2) @ probs - (D @ probs) ** 2`

**Comment by quantshah** [comment]
Thanks @josh146 for explaining that. Will get on to it.
