### ISSUE TITLE
Encrypted tokens in travis

### ISSUE THREAD

**Issue by quantshah** [XanaduAI/pennylane-qiskit#47]
We need to be able to keep up with the IBM API and test with real tokens. 

**Describe the solution you'd like**
I want to discuss putting encrypted variables using travis (
https://docs.travis-ci.com/user/environment-variables/) so that the tests for `ibm.py` work. 

**Describe alternatives you've considered**
Running these tests locally once in a while with private tokens is an alternative. This is especially because we do not necessarily want to run tests on the real IBM device every time someone makes a PR. However, if there is a way to make sure that only after all changes have been implemented, the final version of the PR gets tested on the real device, then it would be great. For this, I suggest that by default, we ignore testing with the tokens (by skipping them when something is WIP) but just before finally merging a PR, we do the test once. This could either be a hook or essential requirement by CI (similar to how every PR needs an approval from a maintainer)

@josh146 This also resolves the lowering of test coverage in the lastest PRs due to ìbm.py`

**Comment by josh146** [comment]
An encrypted IBM Q token has been added to `.travis.yml` in commit 2134385
