### ISSUE TITLE
QiskitError on the data parity function of the pennylane tutorial

### ISSUE THREAD

**Issue by RicardoGaGu** [XanaduAI/pennylane-qiskit#52]
I'm trying to reproduce the data parity variational classifier of pennylane's tutorial collection on the qiskit aer simulator backend,  the following line of code specifies the backend:

```python
dev = qml.device('qiskit.aer', wires=4)

```

This is the variational architecture I'm using, plus the basic data encoding technique _BasisState_ for the bitstring data:

```python
def layer(W):
    qml.Rot(W[0, 0], W[0, 1], W[0, 2], wires=0)
    qml.Rot(W[1, 0], W[1, 1], W[1, 2], wires=1)
    qml.Rot(W[2, 0], W[2, 1], W[2, 2], wires=2)
    qml.Rot(W[3, 0], W[3, 1], W[3, 2], wires=3)

    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[1, 2])
    qml.CNOT(wires=[2, 3])
    qml.CNOT(wires=[3, 0])
    
def statepreparation(x):
    qml.BasisState(x, wires=[0, 1, 2, 3])

```
I get the following the error when I execute the training loop part:

`QiskitError: "Cannot unroll the circuit to the given basis, ['u1', 'u2', 'u3', 'cx', 'cz', 'cu1', 'id', 'x', 'y', 'z', 'h', 's', 'sdg', 't', 'tdg', 'ccx', 'swap', 'multiplexer', 'snapshot', 'unitary', 'reset', 'initialize', 'kraus', 'roerror']. No rule to expand instruction basis_state."`

I sense that the qml.Rot, i.e. the  single arbitrary qubit rotation, is not supported by the Qiskit plugin.

**Desktop**
 - OS: Ubuntu 18.04
 - Version 0.5.1 (pennylane-qiskit)

**Comment by josh146** [comment]
Hi @RicardoGaGu! Can I ask what version of Qiskit you have installed, and what version of PennyLane? The PennyLane-Qiskit plugin defines a [custom `Rot` gate](https://github.com/XanaduAI/pennylane-qiskit/blob/master/pennylane_qiskit/gates.py#L59) that should be qiskit-compatible, so this is a strange error.

**Comment by RicardoGaGu** [comment]
Sorry for the delay Josh!

Here are the versions of the libraries you asked:

- Qiskit version  0.9.0

- Pennylane version 0.5.0

**Comment by josh146** [comment]
Hi @RicardoGaGu, can you try upgrading to the latest version of Qiskit (v0.13) and the latest version of PennyLane and PennyLane-Qiskit?

```
pip install qiskit pennylane pennylane-qiskit --upgrade
```

Let me know if that works for you.

**Comment by RicardoGaGu** [comment]
Same tolerance issue with the following libraries installed in my jupyter kernel:

- Qiskit version  0.10.0

- Pennylane qiskit plugin 0.6.0

- Pennylane version 0.6.0

**Comment by josh146** [comment]
Thanks @RicardoGaGu --- we are looking into the tolerance issue here: https://github.com/XanaduAI/pennylane/issues/365, hopefully we should have a bug fix worked out soon.

In the meantime, does this fix the issue with `No rule to expand instruction basis_state."`? The following code works for me:

```python
import pennylane as qml
dev = qml.device('qiskit.aer', wires=4)

def layer(W):
   qml.Rot(W[0, 0], W[0, 1], W[0, 2], wires=0)
   qml.Rot(W[1, 0], W[1, 1], W[1, 2], wires=1)
   qml.Rot(W[2, 0], W[2, 1], W[2, 2], wires=2)
   qml.Rot(W[3, 0], W[3, 1], W[3, 2], wires=3)
   qml.CNOT(wires=[0, 1])
   qml.CNOT(wires=[1, 2])
   qml.CNOT(wires=[2, 3])
   qml.CNOT(wires=[3, 0])

def statepreparation(x):
    qml.BasisState(x, wires=[0, 1, 2, 3])

@qml.qnode(dev)
def circuit(W, x=None):
    layer(W)
    statepreparation(x)
    return qml.expval(qml.PauliZ(0))

W = np.random.random(size=[4,4])
print(circuit(W, x=np.array([1, 0, 1, 1])))
```
and gives the output `0.3359375`

**Comment by RicardoGaGu** [comment]
Oh yes! Sorry I was executing the amplitude normalization example thinking this was the therad for this issue.

Your example gives me the following error:

`DeviceError: Operation BasisState cannot be used after other Operations have already been applied on a qiskit.aer device.`

Which is solved by putting the statepreparation(x) before the layer(W). Then the outputs keep changing because the layers rotation angles are generated randomly! :) , with a seed should be fixed. The `No rule to expand instruction basis_state` does not appear any longer.

For the data parity

**Comment by RicardoGaGu** [comment]
Oh yes! Sorry I was executing the amplitude normalization example thinking this was the therad for this issue.

Your example gives me the following error:

DeviceError: Operation BasisState cannot be used after other Operations have already been applied on a qiskit.aer device.

Which is solved by putting the statepreparation(x) before the layer(W). Then the outputs keep changing because the layers rotation angles are generated randomly! :) , with a seed should be fixed. The No rule to expand instruction basis_state does not appear any longer.

For the data parity function, I'm still getting the same error even though the kernel has been updated, let me investigate further.

Thank you very much!

**Comment by RicardoGaGu** [comment]
Oh yes! Sorry I was executing the amplitude normalization example thinking this was the therad for this issue.

Your example gives me the following error:

`DeviceError: Operation BasisState cannot be used after other Operations have already been applied on a qiskit.aer device.`

Which is solved by putting the statepreparation(x) before the layer(W). Then the outputs keep changing because the layers rotation angles are generated randomly! :) , with a seed should be fixed. The `No rule to expand instruction basis_state` does not appear any longer.

For the data parity function, I'm still getting the same error even though the kernel has been updated, let me investigate further.

Thank you very much!

**Comment by josh146** [comment]
> DeviceError: Operation BasisState cannot be used after other Operations have already been applied on a qiskit.aer device.

Oops! That was a typo on my behalf. I've edited my comment to switch the order :)

**Comment by RicardoGaGu** [comment]
HI @josh146 , could you try the data parity variational circuit training on qiskit.aer device in your environment/kernel, I'm having the `Cannot unroll the circuit to the given basis` issue even though your example works fine, they have the same single-qubit rotation and two-qubit entangling gates architecture.

**Comment by RicardoGaGu** [comment]
Ok, I found the problem! The data input:

the input `x = [0,0,0,0,0]` produces the `Cannot unroll the circuit to the given basis`. Applyng layer(w) to the all-zero state seems that produces this issue.

**Comment by josh146** [comment]
Ah, that sounds like a bug in how PennyLane-Qiskit defines the basis state operation; we likely need to have an `if-else` in case the ground state is passed.

**Comment by antalszava** [comment]
Hi @RicardoGaGu, thanks for your question! In PR [#60], this issue has been resolved and now it is specifically tested if `BasisState` receives `[0, 0, .. 0]` as input!
